server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.hbm2ddl: trace

spring:
  application.name: demo
  devtools.restart.enabled: true
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3301/test1?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
